### ISSUE TITLE
Using templates

### ISSUE THREAD

**Issue by Delorenzo1000** [ONSdigital/prototype-kit#49]
Hello guys! I have an issue using the design kit. The design system offers the options to prototype using html or nunjuncks. I think this is great BUT the kit template is based on nunjunks only so no possible to use or link to HTML pages. Do we have a template to prototype HTML only...?

**Comment by yatesn** [comment]
Please redirect this question to the discussion forums - https://github.com/ONSdigital/design-system/discussions
