### ISSUE TITLE
Summary manager needs to support 2 or 3 answers on separate lines

### ISSUE THREAD

**Issue by liammcmurray** [ONSdigital/prototype-kit#58]
**Describe the bug**
The summary manager js helper only adds a <br> if there are more than 3 answers. I assume this is for name and date of birth reasons, but it means that two unrelated answer get pushed together on the output.

https://github.com/ONSdigital/prototype-kit/blob/main/src/helpers/summary-manager.js#L76

**To Reproduce**
Steps to reproduce the behaviour:

1. Go to 'https://eq-runner-prototypes.netlify.app/prototypes/prices/'
2. Start survey
3. Continue
4. Add a price and also some text in the comments box
5. Save and continue
7. See the products list page and press continue
8. Repeat steps above for remaining products
9. See the error where price and comments are on same line instead of separated by a <br>

**Expected behaviour**
Unrelated answers should be on new lines

**Screenshots**
See prototype

**Additional context**
We need to be able to decide whether inputs are shown inline or broken onto new lines - sometimes (e.g. Dates) you want on one line, other times it is wrong. Maybe this could be a nunjucks macro option on inputs?

**Comment by liammcmurray** [comment]
Hi @alec-hamilton-ons - thanks for looking. It seems like you need to go through the whole survey to see the summary due to the behaviour of the summary manager. If it has an incomplete list it doesn't generate any results. That's another bug I guess... but for now I've updated the instructions and check and it works as described.

<img width="1112" alt="Screenshot 2023-06-12 at 09 23 42" src="https://github.com/ONSdigital/prototype-kit/assets/3738895/3e028cc0-06b8-40f7-8e73-49f3e1b9642c">

**Comment by alec-hamilton-ons** [comment]
Thanks @liammcmurray, I can reproduce this locally now.
Would you be happy with the fix that all answers are on new lines?
I can't think of any situations where it would be catastrophic if this was the case.

**Comment by liammcmurray** [comment]
Hi Alec - hmmm, really it needs to be configurable due to having name
(first name, last name)  and date (day, month, year) fields that do need to
put multiple answers onto one line. I believe this is why it is currently
set up this way, with the conditional <br> only happening after 3 inputs
(the date scenario - likely from DOB on the census).

Feels like all answers on a new line but with an 'inline' attribute in the
nunjucks macro is the best way forward. I appreciate that is potentially a
fair bit of retooling so worth checking if this a priority with Joe N or
your PM.

**Comment by alec-hamilton-ons** [comment]
Ah OK I see this issue now. I'm looking into the summary macro some more and there's something which might work in your scenario:
if you add multiple objects to the `valueList` array inside the `summaryRowItem,` the macro will give them bullet points. If there's only one object in the array then it won't. Would this be a possible solution to your issue? If not I'll try and make it configurable with an inline flag like you suggest.

<img width="819" alt="image" src="https://github.com/ONSdigital/prototype-kit/assets/132343524/3de2e596-9074-448e-9265-b59d97a505d9">

```
{
                                "rowTitle": "For the period 1 January 2015 to 2 February 2017, what was the value of your total turnover, excluding VAT?",
                                "id": "sales-value-row",
                                "rowItems": [
                                    {
                                        "id": "sales-value",
                                        "valueList": [
                                            {
                                                "text": "£180,440"
                                            },
                                            {
                                                "text": "this is a test comment"
                                            }
                                        ],
                                        "actions": [
                                            {
                                                "text": "Change",
                                                "ariaLabel": "Change answer",
                                                "url": "#0"
                                            }
                                        ]
                                    }
                                ]
                            },
```

**Comment by liammcmurray** [comment]
Hi Alec - yes I can do that. But it's when the summary is automatically generated by the summary manager (a separate js 'helper' in the DS/proto kit that we have the problem - https://github.com/ONSdigital/prototype-kit/blob/main/src/helpers/summary-manager.js#L76
The summary helper is currently the only way to pipe multiple inputs into a summary screen, but it won't list them on new lines unless there are more than three inputs...

Does this make sense?

**Comment by alec-hamilton-ons** [comment]
Hi Liam - yes this makes sense. 
I've had a further look at the summary manager file. This file basically works as the glue between components when prototyping. It saves the questions and answers from previous steps in the questionnaire and then spits everything all out at the end. 
The file itself is responsible for generating the HTML that creates the Summary Table, it doesn't actually use the Summary nunjuck macro from the design system, it does the exact same thing but in a much less customisable way using standard js.
For this reason, I can't change the current macro to support an "inline" flag like suggested, because it won't affect Summary components here in the prototyping kit.
Any changes would need to be made to the `summary-manager.js` file directly.
It's hard to come up with a solution that works for your use case but doesn't break things like Names & Dates and I'm a bit stumped as to what to suggest. I will run this issue past a few of my colleagues to see what they think! Sorry I can't be of more use at this stage!

**Comment by liammcmurray** [comment]
Hey Alec, it's fine - the summary manager feels quite specific and brittle,
I was hoping there might be a simple fix though around a different
conditional statement. e.g. instead of If > 3 answers add <br> could it be
tidied up to For loop through answers and only add <br> if a different
condition is met i.e. ID contains 'return' or some other trigger word. This
feels less like a bug though and more of a rebuild. Might be better to wait
and see what direction we go with the prototype kit in general, as there is
going to be a bunch of issues like this....

**Comment by alec-hamilton-ons** [comment]
Hi Liam,
I've spoken with a few others devs and we agree that we should park this for now. I'm going to raise a spike ticket to properly investigate the prototype kit and how it is used, so we can get a better understanding of the direction it needs to go. If you've got any feedback you can share about what you think the main issues are, that would be a great place to start. Thanks for raising the issue, it's been really interesting investigating this one, albeit a bit frustrating that it's so hard to fix!

**Comment by alec-hamilton-ons** [comment]
Moved issue to blocked and raised #59

**Comment by liammcmurray** [comment]
Hi Alec, yeah this is indicative of several issues with the prototype kit, where it was created for a specific purpose and is not really suitable for more general prototyping. As a design community we have spoken about the situation where there is the gov prototype kit, and then there's the ONS prototype kit and they are similar but also very different and there is no crossover of functionality. I love that you are raising a spike ticket, and would be happy to talk to you about the communities needs and concerns - Joe Nation has a great overview of this and would be a really good person to speak to. We need a resolution though as currently it is not at all easy to prototype.
