### ISSUE TITLE
Open Sans font not loading on prototype kit

### ISSUE THREAD

**Issue by Joe-Dixon-ID** [ONSdigital/prototype-kit#68]
**Describe the bug**
The Open Sans fonts are not loading on the prototype kit

**To Reproduce**

1. Clone the repository of the ONS prototype kit  
2. Launch the prototype
3. Inspect it and it will show 404 errors in the Console because  Open Sans failed to load.

**Expected behavior**
Open Sans should load if its called from css files (and added there correctly).

**Desktop (please complete the following information):**

- OS:  macOS Sonoma 14.1
- Browser Chrome
- Version 120.0.6099.129

**Additional context**
Open Sans loads fine when I inspect the Service manual site so I presume there is a discrepancy between the code thats calls the Open sans font for it to load correctly on Service manual and Prototype kit.

**Comment by alessioventuriniAND** [comment]
This is an issue within the Design system . We need to update the below in the generate-npm-package.js within the ci folder :


from this: 

```javascript
async function copyBaseSassAndFonts() {
  await fs.ensureDir(newSassPath);
  await fs.copy(`${sourcePath}/scss`, `${newSassPath}`);
  await fs.copy(`${sourcePath}/static/fonts`, `${newSassPath}/fonts`);
}
``` 
to this : 

```javascript
async function copyBaseSassAndFonts() {
  await fs.ensureDir(newSassPath);
  await fs.copy(`${sourcePath}/scss`, `${newSassPath}`);
  await fs.copy(`${sourcePath}/static/fonts`, `${cwd}/fonts`);
}
```
